Repository openvinotoolkit/workbench_aux, pull requests merged in 2021-06, with the labels that each got.

#9 [Wrapper] Release Python starter
  starting_package/LICENSE
  starting_package/README.md
  starting_package/__init__.py
  starting_package/openvino_workbench/__init__.py
  starting_package/openvino_workbench/arguments_parser.py
  starting_package/openvino_workbench/constants.py
  starting_package/openvino_workbench/container.py
  starting_package/openvino_workbench/docker_config_creator.py
  starting_package/openvino_workbench/image.py
  starting_package/openvino_workbench/main.py
  starting_package/openvino_workbench/utils.py
  starting_package/requirements-core.txt
  starting_package/requirements-linux.txt
  starting_package/requirements-win.txt
  starting_package/setup.py
Labels: enhancement

#15 [Form] Fix python wrapper cli argument name
  starting_command_form/package-lock.json
  starting_command_form/package.json
  starting_command_form/src/app/shared/components/command-output/command-output.component.scss
  starting_command_form/src/app/shared/constants.ts
  starting_command_form/src/app/shared/models/command-parameter.ts
  starting_command_form/src/app/shared/pipes/command.pipe.ts
Labels: bug

#11 Disable the network connection and pass network name for devCloud
  starting_package/openvino_workbench/container.py
  starting_package/openvino_workbench/docker_config_creator.py
Labels: enhancement

#12 [DOCS] Add instructions on how to publish the starter
  starting_package/DEVELOPER.md
Labels: documentation

#13 [SDL] Add third-party license file for command constructor
  starting_command_form/third-party-programs.txt
Labels: documentation

#17 [WRAPPER] Update wrapper version
  .gitignore
  starting_package/setup.py
Labels: enhancement

#14 [DOCS] Update README
  README.md
Labels: documentation

#18 [58465] [WRAPPER] Lower Docker Python bindings version
  starting_package/requirements-core.txt
  starting_package/setup.py
Labels: bug

#19 [58603] Fix IP forwarding
  starting_package/openvino_workbench/constants.py
  starting_package/openvino_workbench/container.py
  starting_package/openvino_workbench/docker_config_creator.py
  starting_package/openvino_workbench/utils.py
  starting_package/setup.py
Labels: bug

#20 Correct passing ssl params
  starting_package/openvino_workbench/docker_config_creator.py
  starting_package/setup.py
Labels: bug
