Repository openvinotoolkit/workbench_aux, pull requests merged in 2021-07, with the labels that each got.

#23 [Form] [59103] Fix python wrapper parameters got devices in form
  starting_command_form/src/app/shared/models/command-parameter.ts
Labels: bug

#25 [59232] [FORM] Add warning about HDDL daemon should be running
  starting_command_form/src/app/shared/components/result-section/result-section.component.html
  starting_command_form/src/app/shared/components/result-section/result-section.component.ts
  starting_command_form/src/assets/data/messages.json
Labels: feature

#26 [59232] [FORM] Additional instructions for HDDL
  docs/assets/data/messages.json
  docs/index.html
  docs/main.20cbda01ed0f9865ffd4.js
  docs/main.ef304738aa2d788b899e.js
  starting_command_form/src/app/shared/components/result-section/result-section.component.html
  starting_command_form/src/app/shared/components/result-section/result-section.component.ts
  starting_command_form/src/assets/data/messages.json
Labels: feature

#27 [59389] [59553] Introduce stricter rule for container name
  starting_package/openvino_workbench/container.py
  starting_package/openvino_workbench/docker_config_creator.py
  starting_package/openvino_workbench/image.py
  starting_package/openvino_workbench/utils.py
  starting_package/setup.py
Labels: bug

#28 [60414] Introduce the restart option
  starting_package/openvino_workbench/arguments_parser.py
  starting_package/openvino_workbench/constants.py
  starting_package/openvino_workbench/container.py
  starting_package/openvino_workbench/image.py
  starting_package/openvino_workbench/main.py
  starting_package/openvino_workbench/utils.py
  starting_package/setup.py
Labels: bug, feature

#22 [58262] Introduce CI for the Python starter
  .github/workflows/check-python-code.yml
  automation/.pylintrc
  automation/Jenkinsfile
  docs/Install_DL_Workbench.md
  docs/img/Get_Started_Page.png
  docs/img/docker_proxy-b.png
  start_workbench.sh
  starting_package/openvino_workbench/docker_config_creator.py
  starting_package/openvino_workbench/utils.py
  starting_package/requirements-linux.txt
  starting_package/setup.py
Labels: CI

#29 [RELEASE] Bump image version with the latest release (2021.4.0.1)
  starting_package/README.md
  starting_package/openvino_workbench/arguments_parser.py
  starting_package/setup.py
Labels: feature
